import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Todo Kanban",
  description: "Generated by Muhanned Helall",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 antialiased">{children}</body>
    </html>
  );
}
